### ISSUE TITLE
Unit 0 Tips link goes to github

### ISSUE THREAD

**Issue by nathanielgranor** [TEALSK12/introduction-to-computer-science#104]
https://tealsk12.gitbook.io/intro-cs/unit_0/lesson_01

Under "materials", click on "Unit 0 tips", This points to a page in Gitbhub rather than in GitBook. I suspect there may be similar links in other lesson plans and units.

**Comment by aspiece** [comment]
@kenneychan Let's connect on this. The file seems to be in the correct directory and formatting correctly. Let's see if we can sort it out.

**Comment by hollasch** [comment]
_Oif_. This is a poor linking strategy that has popped up in multiple places. For one thing, it's always choosing the `master` branch (or tip of `master`), which makes developmental or release-targeted branches inconsistent. Secondly, it brings up the page in the context of GitHub development, which is unnecessary complication for the reader, who may be unfamiliar with GitHub. Finally, it hard-codes a specific commit, which means that the content of this link will never change, _even if there are subsequent fixes or changes to the file_.

**Comment by aspiece** [comment]
@hollasch Thank you. To be honest, I was just added to the program team and I am working through these and figuring out how to fix things. I find myself in between the novice and intermediate level knowledge using Github. I am hoping someone can help me out figuring this one out. ;)

**Comment by hollasch** [comment]
Feel free to drop me a line at steve@hollasch.net if you have any questions.
