### ISSUE TITLE
Make Snap Tips document into a normal page in Gitbook?

### ISSUE THREAD

**Issue by nathanielgranor** [TEALSK12/introduction-to-computer-science#105]
Is there a reason that the "Snap Tips" document is a separate Word file? It seems like something we'll want to update and do version control on like the rest of the curriculum.

**Comment by aspiece** [comment]
@kenneychan Can you take a look at this and see if you can help me figure out the issue?

**Comment by aspiece** [comment]
Updated link to document in the master
