### ISSUE TITLE
Sample Solution link is broken

### ISSUE THREAD

**Issue by akshaymittal143** [TEALSK12/introduction-to-computer-science#127]
- https://tealsk12.gitbook.io/intro-cs/unit_2/lesson_22#sample-solution link if broken i.e. (404)

**Comment by aspiece** [comment]
Thank you @akshaymittal143 for bringing this to our attention. The sample solutions you can find by accessing the TEALS Dashboard and navigating to Additional Curriculum Materials. I will also update the link to this location.

**Comment by aspiece** [comment]
The link has been updated. Thank you.
