### ISSUE TITLE
Change project 3 "easy" designation to be more sensitive

### ISSUE THREAD

**Issue by nathanielgranor** [TEALSK12/introduction-to-computer-science#128]
Suggest changing the two versions of the Platform Game project description so that the version currently labeled "Project 3" becomes "Project 3 Advanced" and the version currently labeled "Project 3 (Easy)" becomes "Project 3".

This way, students who do the simpler version will not feel put down.

**Comment by aspiece** [comment]
Thank you @nathanielgranor It's been updated
