### ISSUE TITLE
Platform Game project description has hardcoded due dates

### ISSUE THREAD

**Issue by nathanielgranor** [TEALSK12/introduction-to-computer-science#129]
Remove the hard-coded due dates from the Project Description:

Required Checkpoints
Monday, October 27: Screens should be designed; the hero should be able to move and jump; gravity should work; reset button should be functional
Monday, November 3: Hazards and enemies should be present; death should work properly.
Monday, November 10 (final due date): Lives, power-ups, and victory should be implemented; all other required program components must work

**Comment by aspiece** [comment]
Fixed. https://tealsk12.gitbook.io/intro-cs/unit_3/lesson_35/project_3

Thank you @nathanielgranor
