### ISSUE TITLE
Lesson 2.6 - Gravity Model should be moved to Unit 3

### ISSUE THREAD

**Issue by nathanielgranor** [TEALSK12/introduction-to-computer-science#131]
Lesson 2.6 supports the Platform Game project, not pong. In fact there is even a reference to the platform game project. Consider moving this lesson into Unit 3.

**Comment by aspiece** [comment]
Waiting on some clarification with Kenney prior to jumping into this but will be getting this moved as soon as possible.

**Comment by aspiece** [comment]
It's been addressed
