### ISSUE TITLE
Answer key

### ISSUE THREAD

**Issue by johnsonl3986-tech** [TEALSK12/introduction-to-computer-science#140]
We are on the Lab 1.1.1 Snap Begins. I do not have the answer key. Students are asking questions I can't answer. How do I get access to the answer keys for Intro to CS curriculum?

**Comment by checopdleon** [comment]
If the students are asking about the functionality of features like blocks, etc., then I would suggest the Snap resources, https://cloud.snap.berkeley.edu/snapsource/help/SnapManual.pdf, or https://forum.snap.berkeley.edu

Another good place to ask for help, of any kind, would on the Teals forum, https://forums.tealsk12.org

Hope that helps!
Good vibes!

**Comment by aspiece** [comment]
We have sample solutions and answer keys available in "Additional Curriculum" Materials in the TEALS Dashboard. If you are having trouble getting access or finding anything, feel free to reach out to your Regional Manager.
