### ISSUE TITLE
Curriculum Map doesn't reflect new structure

### ISSUE THREAD

**Issue by zimmi88** [TEALSK12/introduction-to-computer-science#15]
Updates appear to have been made to the markdown pages that aren't reflected in the curriculum map.

- Pong and Platform Game appear to have been swapped in the course structure.
- Variables now appears to be a part of Unit 2.

**Comment by kenneychan** [comment]
Then new structure has been fixed in PR 14 https://github.com/TEALSK12/introduction-to-computer-science/pull/14
