### ISSUE TITLE
Fix links that lack explicit targets

### ISSUE THREAD

**Issue by hollasch** [TEALSK12/introduction-to-computer-science#157]
A good deal of our links were authored early to omit their target component. These look like `This is a [jump to some target] in the text.` Some renderers will interpret this as `[jump to some target][]` (a deferred link using the link text), and other renderers will interpret this as regular text with square brackets.

For all links that _do_ have deferred defintion, we should append the `[]` component to make the link nature unambiguous.

**Comment by aspiece** [comment]
Thank you Steve.
