### ISSUE TITLE
Review Do Nows for 2.2 and 2.3 - switch them?

### ISSUE THREAD

**Issue by markzachar** [TEALSK12/introduction-to-computer-science#164]
Lessons 2.2 and 2.3 do now's seem to be flipped in the wrong order.

**Comment by aspiece** [comment]
I see why they did this in this order. Using Blooms, it takes the students up the spectrum. 2.1 identifies the loop and then 2.2 is similar to PArsons problem which is a higher order thinking skill. As they learn more about loops they are able to move to deeper knowledge and able to apply what they learned easier.
