### ISSUE TITLE
Alternate lab 3.4

### ISSUE THREAD

**Issue by SebastianJay** [TEALSK12/introduction-to-computer-science#187]
Offering an alternate approach to lab 3.4. My goals for modifying the lab spec were:

* Providing clear directions about what each block should do. I added images of each custom block into the lab doc, as well as sample inputs/outputs for students to test on their own.
* Reinforcing that custom block implementations can leverage other custom blocks. The lab is designed for students to build on their work.
* Removing material on strings, which I hadn’t covered and wanted to keep out of unit 3.
* Showing something cool on stage. Labs 3.3 and 3.4 get away from using the stage, which might cause students who aren’t interested in just reporting values (it’s more abstract than most things they’ve done up to this point) to struggle or check out. Showing students the completed lab before they start could be a good hook and provides some context for the “low level” blocks they’re making in the beginning. Just make sure they follow the doc in order and don’t try jumping ahead!

Lab spec: https://docs.google.com/document/d/1Upr82OzadeH69qq0kRpnpw2qU6GgRwhb4hbNXwcZtyw/edit?usp=sharing

**Comment by aspiece** [comment]
Thank you @SebastianJay . I have already started some preliminary work on this curriculum with some formatting clean up. I plan to jump on deeper once we move into second semester. I will let you know if I have any questions. ;) 
--Andrew
