### ISSUE TITLE
For loop missing from curriculum

### ISSUE THREAD

**Issue by baseballpoetess** [TEALSK12/introduction-to-computer-science#193]
Somewhere in the updates, Snap! added a For loop.  This should be part of lesson 2.1 which covers Forever, Repeat [], and Repeat Until [].  

![For loop](https://user-images.githubusercontent.com/27076341/72467831-67441980-37a1-11ea-95c4-c5b6c76c9f1b.png)

**Comment by aspiece** [comment]
For loops is covered in the second semester of the Intro to CS pathways. It is not a skill taught in this course. Thank you for your feedback.
