### ISSUE TITLE
Lesson 4.6 sample word guessing game needs replacement

### ISSUE THREAD

**Issue by felixtsem5** [TEALSK12/introduction-to-computer-science#196]
The sample word guessing game listed on [Lesson 4.6](https://github.com/TEALSK12/introduction-to-computer-science/blob/master/lesson_46.md) does not seem to work for a few people on our team. Not sure if it's affecting everyone or just us.
http://www.searchamateur.com/Play-Free-Online-Games/Bubbletoonia-Cake-Deal.htm

There is another sample game that is listed on [Do Now 4.6](https://github.com/TEALSK12/introduction-to-computer-science/blob/master/do_now_46.md) that can be a potential replacement.

**Comment by aspiece** [comment]
Replaced with a PPT game called Spaceman including a video tutorial on the game. Due to needing the Flash plug in, it made more sense this way. 

Also, Added a demo video in the 4.6 project to see the project running. ;)
