### ISSUE TITLE
The Unit 1 Quiz link gives a 404 Error.  it's a link to a "Unit 1 Quiz.docx" but it's broken

### ISSUE THREAD

**Issue by Blackbaud-PeteLukich** [TEALSK12/introduction-to-computer-science#20]
The Unit 1 Quiz link gives a 404 Error.  it's a link to a "Unit 1 Quiz.docx" but it's broken

**Comment by kenneychan** [comment]
Hi Peter, you should be able to access the quizzes from the TEALS dashboard under additional curriculum materials. Kenney
