### ISSUE TITLE
6.3 in need of samples (semester 1) 

### ISSUE THREAD

**Issue by LuciaBerliner** [TEALSK12/introduction-to-computer-science#202]
6.3 lacks samples for the steps of project development. Teachers are specifically requesting examples of "scenarios" and "wire framing" as they relate to this project.

**Comment by aspiece** [comment]
We have updated the guidance in Unit 6 to allow for teachers to use any project management process. Also added some missing documents that were missed in our transition to HTML. Unit 6 was in need of restructuring and was missed in the transition.
