### ISSUE TITLE
Semester 2 - Lab 3.03 Misaligned with Student Prior Knowledge

### ISSUE THREAD

**Issue by LuciaBerliner** [TEALSK12/introduction-to-computer-science#211]
EMAIL FROM TEACHER: 

Hi Lucia,

I hope you're doing well in these unusual times.

I wanted to share my thoughts on lab 3.03 for python. I was working on it myself so I'd have an idea of what difficulties the kids might encounter, and for the first time, I threw in the towel. I thought I could've done the lab using just one function, but to use two was driving me crazy. I checked the solution on the TEALS website, and thought 1) this was far too complicated for my students, and 2) the solution doesn't relate to the lesson because the the second function doesn't use the return value from the first function, so what was the point of having the first function return a value.

I don't know whether other teachers have had similar experiences, but my feeling is that in future years, TEALS may want to consider using a simpler lab instead. Just a thought.

Stay safe,

Jory

**Comment by degriff** [comment]
I have taught a variety of computer languages in the post-secondary environment,  Only one of the used keywords to distinguish subroutines from functions.  I believe that this was the intention of this lesson.  This teacher does a good job articulating that the target was missed.

**Comment by aspiece** [comment]
We have it planned to look at the answer keys in Python. This should help with this. To track to the progress, feel free to post in that paste this issue in that repo.
