### ISSUE TITLE
Lesson 3.5 links to Advanced Platform Game broken

### ISSUE THREAD

**Issue by mholthouse** [TEALSK12/introduction-to-computer-science#22]
https://tealsk12.gitbooks.io/introduction-to-computer-science/content/Projects/Projects%20Word/Project%202%20Platform%20Game.docx

https://tealsk12.gitbooks.io/introduction-to-computer-science/content/Projects/Projects%20PDF/Project%202%20Platform%20Game.pdf

Both refer to Project 2; should be Project 3

**Comment by kenneychan** [comment]
@mholthouse fixed in #27, thanks for pointing this out.
