### ISSUE TITLE
Do now 1.1 Snap

### ISSUE THREAD

**Issue by aimeerosato** [TEALSK12/introduction-to-computer-science#235]
In the HTML version it's really confusing to try to match the curves with the chart. Are there alternative activities that are remote-friendly? This seems ideal for a pen and paper situation.

**Comment by aspiece** [comment]
@aimeerosato This can easily be adapted to an online version using Desmos. When you say the html version is confusing, is the PDF easier to match the curves? I was considering using an easier image like a shape. Do you think it would make the assignment less confusing if there were fewer curves or maybe they were all line segments?
