### ISSUE TITLE
Do Now 2.4 is very open-ended

### ISSUE THREAD

**Issue by Dan-TEALS** [TEALSK12/introduction-to-computer-science#237]
Do Now 2.4 has a very minimalist description, basically:
- Here's a Snap! program.
- We say there are three bugs.
- We're not going to tell you what the program does or what the expected behavior is - you need to figure that out.

To complicate matters further, there is no discussion of a solution to the Do Now or expected behavior in the lesson plan or the slide deck.

**Comment by aspiece** [comment]
@Dan-TEALS  From what I can tell, this was meant to be open-ended. Do you think adding a discussion to the beginning of the lesson will resolve this?

I noticed that this isn't the first time we use debugging with the students. Do you think they will understand what to do based on the previous activities that include debugging or do you think they need more explanation prior to doing this activity?

**Comment by Dan-TEALS** [comment]
I don't see how a debugging problem can be open-ended. By definition, debugging requires expected outputs to given inputs. In the Do Now, we don't tell the students what the expected behavior of the program is, just that there are three bugs (which are not really obvious) that they need to fix. To take this back to Bloom's Taxonomy, we are asking the students to perform an analysis-level task using skills (conditionals) they were just introduced to in the last lesson in a Do Now that's only supposed to take 5 minutes. To make matters worse, unlike many of the Do Nows, there's no discussion of the solution in the lesson plan or slides - it just jumps right into the instruction. Obviously, there is a "right answer" or we wouldn't say there are three bugs that need to be fixed. (I've found the three bugs, to be honest, they're not that obvious.) An open-ended problem would be something like: "In this game, Alonzo chases the Blue Dog. How would you modify this game to make it more fun to play?" But that's still too much for a Do Now.
