### ISSUE TITLE
2.02/2.03 Issue with Prior Knowledge

### ISSUE THREAD

**Issue by nagmateals** [TEALSK12/introduction-to-computer-science#265]
Unit 2.02 covers booleans. But the lab for figuring out if someone can be president or ride a rollercoaster clearly requires conditionals as well. That is not covered until 2.03.

**Comment by gilpin-bmchs** [comment]
you don't have to use conditionals...

# Can I ride the rollercoaster?
# gather user information
height = int(input("How tall are you in inches? "))
age = int(input("How old are you? "))
quarters = int(input("How many quarters do you have? "))
freq_pass = input("Do you have a frequent rider pass? ")

can_ride = (height > 50 and age > 18 and quarters >= 4) or (height > 50 and age > 18 and quarters >= 2 and freq_pass == 'yes')
print(can_ride)

**Comment by dvgrn** [comment]
Yup, this is the teaching material's attempt to break things up into bite-sized pieces -- Boolean expressions first, and then the conditionals that use them in the next unit.

It's absolutely true that any sane programmer would use conditionals to solve this problem, though.  So maybe we need an extra hint to students and volunteers here:  "This can be done without the use of if statements, which will be covered in the next unit."

A sample solution for this lab would be one possible source of hints.  At the moment we have sample solutions only for 2.03, 2.04 and 2.07 -- it would be a good goal to have a solution available for every lab.

**Comment by gilpin-bmchs** [comment]
Agreed.  It is unintuitive to solve it this way.  I agree, there should be
a note for the teacher/volunteer to point this out so they don't get
confused.  The student should be fine as they shouldn't know what
conditionals are yet anyway.
