### ISSUE TITLE
Old Gitbook

### ISSUE THREAD

**Issue by aimeerosato** [TEALSK12/introduction-to-computer-science#278]
https://tealsk12.gitbook.io/intro-cs/ still lives! Can we redirect people to the new curriculum page or make it clear that this version is depreciated?

**Comment by aspiece** [comment]
@aimeerosato Currently, all updates are being applied to both location due to the process we are using. Due to legacy users of the curriculum, we felt leaving it live would avoid any links being broken. This gives the opportunity for organizations the time to update their links on their end.

**Comment by aimeerosato** [comment]
Ok so I will alert you to things I notice.  In the old site, do now 3.2 is
misnamed "Drawing Squares" and should be updated.

**Comment by aspiece** [comment]
Great catch. I found the error in both versions and made the name of the Do Now consistent.
