### ISSUE TITLE
Lesson 0.1 video has been made private

### ISSUE THREAD

**Issue by jdonwells** [TEALSK12/introduction-to-computer-science#311]
From the lesson plan at https://github.com/TEALSK12/introduction-to-computer-science/blob/master/lesson_01.md there is a link to a Youtube video at https://www.youtube.com/watch?v=cKhVupvyhKk. That video is showing up as being private.

**Comment by dsiegel** [comment]
The video got updated here: https://github.com/TEALSK12/introduction-to-computer-science/commit/ab66af8bffff7df8c6196a31a97ebc3e5e3abaed

The new video doesn't seem right though. Not sure what you're supposed to do with it.

**Comment by aspiece** [comment]
Thank you @jdonwells  and @dsiegel the video has been removed.
