### ISSUE TITLE
Curriculum map formatting is off

### ISSUE THREAD

**Issue by aimeerosato** [TEALSK12/introduction-to-computer-science#332]
Curriculum map seems to be rendering strangely. The table is disorganized / formatting is off.

**Comment by nikmolnar** [comment]
I'm also seeing an issue with formatting on the curriculum map page, as are several others currently in the TEALS Meetup #1. It looks like the table formatting is off.

<img width="1077" alt="Screen Shot 2021-09-30 at 7 28 55 PM" src="https://user-images.githubusercontent.com/2422416/135556345-a516696c-7dac-430b-8383-601f457f71ea.png">

**Comment by nikmolnar** [comment]
I think this change to the build file may be the cause: https://github.com/TEALSK12/introduction-to-computer-science/commit/3382ba3c81df2de303d2a501425a7bfb2ae1977b#diff-40f75eb334a09bac5ac6ef3482f9725fa9d6cb4580bead16bad2033adb94ad30L28-R43

Each row of the table was on a single line before, and now lines are wrapped. I believe Markdown tables require one line per row.

**Comment by aspiece** [comment]
Thank you @nikmolnar . It's in the PR I have waiting on review to be fixed. Sorry for any confusion.
