### ISSUE TITLE
3.2 enough said.

### ISSUE THREAD

**Issue by jdonwells** [TEALSK12/introduction-to-computer-science#345]
Just looking at 3.2.

In SUMMARY.md it says "Do Now 3.2: Drawing Squares". I don't think that title is correct. The document says "Sprite Control".

paragraph after 4.1. There is no change in y block there is only a change y by block. 

In general 3.2 is confusing. I have a longer rant about it here [https://github.com/TEALSK12/introduction-to-computer-science/discussions/344](https://github.com/TEALSK12/introduction-to-computer-science/discussions/344)

**Comment by aspiece** [comment]
Thank you Don. The Summary.md file was used to interface with Gitbook. Since Gitbook has been retired, I am going to delete the file from the repo. I will look at #344  next. 

Thank you., Keep them coming.
