### ISSUE TITLE
lab_42 there is no 1.2

### ISSUE THREAD

**Issue by bospoort** [TEALSK12/introduction-to-computer-science#360]
The first bonus on part 2 says "Modify your script so that a noun phrase can either be the construction from part 1.2 "

But there is no part 1.2.

Please fix.

**Comment by nikmolnar** [comment]
More specifically, the [HTML version](https://tealsk12.github.io/introduction-to-computer-science/lab_42.md.html) of the lab has broken formatting, and the [Word](https://github.com/TEALSK12/introduction-to-computer-science/raw/master/Unit%204%20Word/Lab%204.2%20You%20Talkin%20To%20Me.docx) and [PDF](https://github.com/TEALSK12/introduction-to-computer-science/raw/master/Unit%204%20PDF/Lab%204.2%20You%20Talkin%20To%20Me.pdf) versions are missing a lot of material (as @bospoort points out).

**Comment by nikmolnar** [comment]
This issue should be reopened (it doesn't look like I can do this). #371 does not resolve this issue. The PR includes changes to the 4.2 slidedecks, but not any of the 4.2 lab documents.
