### ISSUE TITLE
TEALS SNAP 5.2.pptx missing resource?

### ISSUE THREAD

**Issue by jdonwells** [TEALSK12/introduction-to-computer-science#365]
Slide 8 of the file TEALS SNAP 5.2.pptx says "This lab will largely duplicate the code shown in the lecture part of the lesson." Given that there is no code included in the lesson how can we know they will want to duplicate it? Slide 7 says to demo the use of two blocks presumably that is when the code is shown. It would be best I think to standardize the code being shown.

**Comment by AimeeMRosato** [comment]
Thanks for your comment! It looks like the current PPT is updated.
