### ISSUE TITLE
Errors in lab names in curriculum map

### ISSUE THREAD

**Issue by Dan-TEALS** [TEALSK12/introduction-to-computer-science#395]
There are some typos and at least one incorrect name in the _Curriculum Map_. A few I noticed in a cursory glance at the map were:
- The expectation when seeing a lab listed in the table is that there's an associated handout, but 0.1, 0.2, and 0.3 don't have a lab handout
- Lab 2.2 has the name _Another Brick in the Wall_, not _Yellow Brick Road_.
- Lab 2.5 should be _Triangle_**s** _of All Kinds_
- Lab 6.2 has the number of days instead of _Final Project_

**Comment by AimeeMRosato** [comment]
#444 Thanks for flagging, fixed!
