### ISSUE TITLE
lab_05.docx wrong link

### ISSUE THREAD

**Issue by jdonwells** [TEALSK12/introduction-to-computer-science#396]
The lab_05.docx document has the Peabody test at https://snap.berkeley.edu/snap/snap.html. But that is just the generic open an empty project link.

It should also be noted that the pdf version has no link. 

Perhaps the link should also be in the document in clear text?

Is this Peabody test similar to the Peabody Developmental Motor Scales test? It doesn't seem like it from the description.

**Comment by jdonwells** [comment]
I found the link in the PowerPoint presentation speaker notes. https://snap.berkeley.edu/snap/snap.html#present:Username=georgesb&ProjectName=coordinatesTest&editMode&noRun

**Comment by AimeeMRosato** [comment]
Thanks! I see the correct link in the Word document now. Closing this comment.
