### ISSUE TITLE
Link broken on 2.4 pptx slide 4

### ISSUE THREAD

**Issue by lizPayson** [TEALSK12/introduction-to-computer-science#404]
The link on slide 4 of the 2.4 slide deck should go to a snap project for the Do Now exercise, but there doesn't seem to be anything at that link. I ran into another broken Do Now link in a previous slide deck but I don't remember which one (somewhere in unit 1, i believe it involved introducing students to broadcasting messages)

The link in question: https://aka.ms/DoNow2.4

When I open this, it takes me to some generic Bing search page.

**Comment by aspiece** [comment]
All set.
