### ISSUE TITLE
Broken link Lab 2.3

### ISSUE THREAD

**Issue by jpfasano** [TEALSK12/introduction-to-computer-science#409]
On page https://tealsk12.github.io/introduction-to-computer-science/lab_23.md.html the hyperlinked text **Planning Worksheet** in the sentence _Fill out a [planning worksheet](https://github.com/TEALSK12/introduction-to-computer-science/raw/master/SNAP%20script%20Design%20and%20Planning%20Worksheet.docx) for the above script_ is a broken link.

**Comment by AimeeMRosato** [comment]
Thanks, JP! I just cleaned this up.
