### ISSUE TITLE
Do Now 1.4 redirect link is dead

### ISSUE THREAD

**Issue by jalexchapman** [TEALSK12/introduction-to-computer-science#416]
Lab 1.4 slides point to http://aka.ms/DoNow1.4 but this now redirects to www.bing.com. Can whoever owns these redirects fix this?

The correct redirect target is https://snap.berkeley.edu/snap/snap.html#present:Username=andrewspiece&ProjectName=Do_Now%201.4_Starter

**Comment by AimeeMRosato** [comment]
Thanks for flagging! Fixed.
