### ISSUE TITLE
This repo needs a large refactor + cleanup

### ISSUE THREAD

**Issue by hollasch** [TEALSK12/introduction-to-computer-science#44]
It needs a sensible directory structure, and file references will need to be updated (for the GitBook materials).

**Comment by SebastianJay** [comment]
Is there an idea of what a good end state looks like? I could spend some effort here.

**Comment by hollasch** [comment]
Unfortunately, the repo is in a difficult state now with the CA-2018 branches. These have not been architected with a vision for future development, and has effectively grown into a parallel fork with ongoing cross-fork integrations. At this point, I don't even know if cherry-picking common changes will work from one branch to the other.

Given this, any reorganization would be a nightmare, unless you were willing to perform each change twice. We should probably wait to see if this issue resolves first.

**Comment by hollasch** [comment]
That's the Canadian curriculum.

**Comment by aspiece** [comment]
I will see what I can clean up in the next release. I am hoping to have a release out before the end of 2019.

**Comment by hollasch** [comment]
Take a look at the APCSA project/curriculum structure as a possible target.

**Comment by aspiece** [comment]
@hollasch Thanks. Definitely something I am striving for. Get used to things right now. ;)
