### ISSUE TITLE
Link to "Chalk Talk" in Lesson 0.2 appears to be broken

### ISSUE THREAD

**Issue by daprahamian** [TEALSK12/introduction-to-computer-science#47]
The link to http://www.nsrfharmony.org/system/files/protocols/chalk_talk_0.pdf# returns a 404 page.

It appears that there is a valid link here: https://www.nsrfharmony.org/wp-content/uploads/2017/10/chalk_talk_0.pdf

**Comment by aspiece** [comment]
This has been corrected. See page here - https://tealsk12.gitbook.io/intro-cs/unit_0/lesson_02
