### ISSUE TITLE
Unit 2 BJC video suggestions don't match lessons

### ISSUE THREAD

**Issue by nathanielgranor** [TEALSK12/introduction-to-computer-science#51]
The BJC video suggestions in Unit 2 don't seem to line up with the topics. Perhaps this is an artifact of when we swapped unit 2 and 3 projects?

- Lesson 2.1 is about loops, but videos are about functions
- Lesson 2.5 is about Booleans, but video is about history of video games and designing casual games
- Lesson 2.6 is about combining loops and conditionals, but video is about video games
- Lesson 2.7 is the pong project, but video is recursion (spelled wrong)

**Comment by aspiece** [comment]
BJC videos have been removed from Unit 2 lessons.
