### ISSUE TITLE
Printing PDF

### ISSUE THREAD

**Issue by aimeerosato** [TEALSK12/introduction-to-computer-science#59]
Since Gitbook updated, this no longer works: "The Introduction to Computer Science GitBook can be printed by navigating to https://www.gitbook.com/book/tealsk12/introduction-to-computer-science/details, clicking the "Download PDF" in the upper right corner, and selecting the pages to print."

NY/NJ RMs need to be able to print this this week.

**Comment by juliusgawlas** [comment]
Same problem here - any update on a resolution or a workaround?
Thanks!

**Comment by hollasch** [comment]
We can generate a printable version by

1. concatenating all of the Markdown sources listed in `SUMMARY.md`,
2. running [grip](https://github.com/TEALSK12/apcsa-instructor/wiki/Grip) to generate the HTML,
3. saving the generated HTML to some directory,
4. tweaking Chrome to use style `page-break-before: always;` in the user agent CSS, and
5. printing the resulting web page to PDF.

Now that I know the steps, it's not too bad. Here's the latest result: [intro-book.pdf](http://teals.hollasch.net/intro-book.pdf).

This should do for now; there are better options than GitBook that we're investigating.

**Comment by juliusgawlas** [comment]
Thanks!

Indeed it pretty reasonable workaround. I have downloaded created pdf and will be using it.
