### ISSUE TITLE
Lab 5.2 Video Unavailable

### ISSUE THREAD

**Issue by amberteals** [TEALSK12/introduction-to-computer-science#85]
Link to Space Invaders video takes you to a youtube error screen that says the video is unavailable.

**Comment by aspiece** [comment]
Hello @aimeerosato ! Is this link still located in Lab 5.2? I don't seem to see it here - https://tealsk12.gitbook.io/intro-cs/unit_5/lesson_52/lab_52

**Comment by aspiece** [comment]
Video link has moved or has been deleted. @amberteals let me know if I missed something. --Andrew
